import { Toaster } from "@/components/ui/toaster";

import "@/app/globals.css";
import NavBar from "@/components/NavBar";
import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";

const vazir = Vazirmatn({ subsets: ["arabic"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa_IR" dir="rtl">
      <body className={vazir.className}>
        <NavBar />
        <main>
          {/* <LeftSidebar></LeftSidebar> */}
          <section>{children}</section>
          {/* <RightSidebar></RightSidebar> */}
        </main>
        <Toaster />
        {/* <Footer></Footer> */}
      </body>
    </html>
  );
}
